dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - dev

install:
# Install other pip dependencies
- pip install nbconvert requests jinja2 mkdocs mkdocs-material pygments pymdown-extensions mkdocs-exclude
# Install this one after or it raises an error
- pip install mknotebooks

script: true

before_deploy:
# Prebuild mkdocs site documentation
- mkdocs build --verbose --clean

deploy:
# Deploy package to pypy
- provider: pypi
  user: aleg
  password: "$PYPI_PW"
  server: https://test.pypi.org/legacy/
  on:
    branch: dev

- provider: pypi
  user: aleg
  password: "$PYPI_PW"
  on:
    branch: master

# Deploy mkdoc documentation to github page
- provider: pages
  skip_cleanup: true
  target_branch: gh-pages-test
  github_token: "$GH_TOKEN"
  local_dir: site
  on:
    branch: dev

- provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: site
  on:
    branch: master
