# Required python packages to generate the documentation
# * mkdocs
# * mkdocs-material
# * pygments
# * pymdown-extensions
# * mknotebooks

# Project information
site_name: 'NanopolishComp'
site_description: 'Python package for upstream preprocessing and downstream analysis of nanopolish'
site_author: 'Adrien Leger'
site_url: 'https://a-slide.github.io/NanopolishComp/'

# Repository
repo_name: 'a-slide/NanopolishComp'
repo_url: 'https://github.com/a-slide/NanopolishComp'

# Copyright
copyright: 'Copyright &copy; 2019 Adrien Leger'

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - Usage:
        - How to use NanopolishComp: usage.md
        - Eventalign_collapse usage: demo/Eventalign_collapse_usage.ipynb
        - Freq_meth_calculate usage: demo/Freq_meth_calculate_usage.ipynb
    - Contributing: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md

# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: a-slide
      repo: NanopolishComp
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mknotebooks
